Downgraded rcloud-base
Latest release of rcloud-base has breaking changes.
The prompt build is failing
```
./main.go:89:33: not enough arguments in call to authv3.NewAuthMiddleware
	have (authv3.Option)
	want (authv3.Option, *bun.DB)
```

Prompt does not require db connection. There is not point in creating
db connection for AuthMiddleware in the Prompt code. Instead we can
handle creating db connection in Auth constructor.